dsharlet/array

- array.h
- test/errors.cpp
- test/matrix.cpp
- test/shape.cpp
- Add `transpose`/`reorder` for `array`/`array_ref`, and make the existing `transpose`/`reorder` specific to shapes.
- Rename `reorder` -> `transpose`, `select_dims` -> `reorder` (matches numpy more closely).
- Require `transpose` to be a permutation.
Also some driveby comment improvements.
> Improve reorder/transpose

- array.h
- examples/linear_algebra/Makefile
- examples/linear_algebra/einsum.cpp
- examples/linear_algebra/einsum.h
- examples/linear_algebra/matrix.cpp
- test/errors.cpp
There's still a lot that could be done here, but this turned out to be fairly complete as a zero cost compile-time abstraction for Einstein summation.
This lacks any kind of clever optimization, but when this is used inside a manual tiling loop, it is still very expressive and should produce good performance with no overhead (see `multiply_einsum_tiles` for example, although it doesn't actually produce good performance today, hopefully due only to https://bugs.llvm.org/show_bug.cgi?id=45863).
> Add einsum function in the linear_algebra examples

- array.h
- examples/linear_algebra/matrix.cpp
- test/einsum.cpp
Not completely sure this is a good idea, but it makes `make_einsum` a bit nicer for scalar results...
> Add implicit conversion to value_type for scalar-shaped arrays

- Makefile
- README.md
- test/build_test.cu
- Added some short docs about CUDA support to the readme.
- Tweaked Makefile to try to get the outputs to go in bin/ obj/ but failed.
- Drive-by change to run the errors test first, since it's fast, and it's annoying to wait for the performance tests to run when checking this.
> Add CUDA blurb to readme, and small tweaks to build.

- array.h
- test/array.cpp
- test/shape.cpp
- test/test.h
Verified this works by making part of the for_each_index implementation take the function by value, the build broke.
> Add tests that function-accepting functions do not copy the function.

- array.h
- examples/resample/resample.cpp
- test/array.cpp
- test/array_ref.cpp
Now that `make_compact` produces a dense shape in the typical no-strides case, I think `make_dense` and related functions are unnecessary, but I'm not sure, @jiawen what do you think?
I think the best improvement if/after merging this would be to find a clean way of addressing #23, which in combination with make_compact, would be a 1:1 replacement for make_dense.
> Remove make_dense and friends

- array.h
- test/array.cpp
This helper allows move constructing an array to another array with a shape of a different type, which was previously not possible. This function is similar to the existing `reinterpret_shape` helper, but returns a move constructed array from the argument.
This PR also adds a check that when converting shapes, dimensions that are sliced off are trivial.
> Add move_reinterpret_shape

- array.h
An upcoming compiler release updates libc++ to stop exporting `<algorithm>`
from certain headers [1]. This means code using functions from `<algorithm>`
but relying on them existing from transitive header dependencies will now be
broken.
[1] The commit: https://github.com/llvm/llvm-project/commit/2e2f3158c604adb8401a2a44a03f58d4b6f1c7f9
> Add missing `#include <algorithm>`

- BUILD.bazel
- array.h
- test/array.cpp
* Fixes missing array.cpp from Bazel test.
> Adds variant of make_copy that doesn't need the destination shape.

- Makefile
- array.h
- test/readme.cpp
This fixes #67, and a few other issues with GCC 9.4.
> Help GCC 9.4 with ambiguous overloads

- array.h
- test/shape.cpp
This adds a helper shape type `fixed_dense_shape<Extents...>` that defines a fully constant shape. I think this is the "hard part" of #65, the rest is easily done in user code.
> Add `fixed_dense_shape` (related to #65)

- array.h
This mirrors the templated accessor added on array:
template <size_t D, class = enable_if_dim<D> const auto& dim()
Both accessors still forward calls to the underlying shape_.
> Add dim(size_t d) overload to class array

- array.h
This mirrors the templated accessor added on array:
template <size_t D, class = enable_if_dim<D> const auto& dim()
> Add dim(size_t d) overload to class array_ref

- test/algorithm.cpp
Before this change, `make test` gives:
```
g++ -I. -c -o obj/test/algorithm.o test/algorithm.cpp  -O2 -ffast-math -fstrict-aliasing -fPIE  -std=c++14 -Wall
test/algorithm.cpp: In function ‘void nda::test_transform_index_body()’:
test/algorithm.cpp:125:34: error: call of overloaded ‘array(<brace-enclosed initializer list>)’ is ambiguous
125 |   dense_array<int, 1> a_1d({1024});
```
> algorithm.cpp: Add initializer to pacify gcc

- absl/absl.h
- absl/absl_test.cpp
- include/array/array.h
- test/array.cpp
- test/shape.cpp
This makes things a bit more clear, and might make debugging a bit easier (-9 is a not-totally-unreasonable value to see in memory).
The absl changes are a yolo commit, I spent a few minutes trying to install bazel on windows subsystem for linux and ran into issues. It's *probably* right but could easily be broken.
> Use a new token `unresolved` instead of `dynamic` for unresolved strides

- include/array/array.h
- test/array_lifetime.cpp
- Don't construct an allocator if we're going to move it from another container.
- Fix copies due to use of `select_on_container_copy_construction`.
- Fix warnings about C++17 usage from #88.
- Add a lot more test coverage of allocator lifetimes.
> Better accounting and fixes of allocator lifetimes

- include/array/array.h
- test/shape.cpp
- When setting a static stride to any other value, asserts that the value equals the static value.
- This allows shapes where some strides are static to be constructed or assigned to unresolved shapes.
> Allow assigning unresolved to a static dim stride as a noop.

- include/array/array.h
- test/shape.cpp
Fix for Issue [#91](https://github.com/dsharlet/array/issues/91). Adjusts automatic stride calculation to improve an edge case where single-row images were getting assigned a y-stride of 1, rather than the number of row elements. (Similarly for plane-stride of planar images with a single plane.)
> Adjusts stride calculation for single-row interleaved or single-plane planar images.

- include/array/array.h
This fixes an issue I noticed with @fbleibel-g where calls to `resolve_unknown_strides` was getting called in an example where I didn't expect it. This modifies some uses of `array_ref::array_ref` to use the non-resolving version of the constructor when we're using a shape that should have already been resolved.
This is a bit of a dangerous change, it's possible that some wonky usage of the array library could result in unresolved shapes getting resolved via these calls, but IMO that would be a bug if that were the case, that should be fixed elsewhere.
> Use non-resolving version of array_ref::array_ref where appropriate

- include/array/array.h
Clarify that stride is in number of elements, not bytes. This can be confusing for users coming from other libraries.
> Document units for `stride`
